### ISSUE TITLE
fleet url

### ISSUE THREAD

**Issue by hamcybo** [BenHUET/eveseat-calendar#11]
does the addon use of fleet URL?

**Comment by warlof** [comment]
If what you want is handling invite based on fleet URI, answer is no.

The PAP mechanic is using ESI based on the active character on SeAT (from profile) in order to retrieve the associated fleet and list all its members.

**Comment by hamcybo** [comment]
if I understand it, it looking at each character, then checking to see if they are in a fleet with the same name. like CTA xyz.

**Comment by warlof** [comment]
nah, much more easier.

On SeAT, you have a "main character" which is defined in your user profile and displayed on the sidebar.
On the calendar, you have an extra "pap" button near all OP on which your character is the FC.
When you hit it, it will :
1) call ESI in order to return your Fleet (you need to be boss)
2) call ESI in order to retrieve all your fleet members
3) add the greatest value tied to the tag assigned to the papped OP to each of them

**Comment by warlof** [comment]
Closing the issue since it has not been update for weeks.
Fill free to reopen it if you're still stuck.
